# Generated by Django 6.0.5 on 2026-05-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbTipoFuncionario',
            fields=[
                ('id_tipo_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_funcionario', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'tb_tipo_funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbTipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_usuario', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tb_tipo_usuario',
                'managed': False,
            },
        ),
    ]
